/**
 * Mock data for UI development while backend (SET-03) is being built.
 * All types come from @cs/domain.
 */
import type {
  Project,
  StrategicMetrics,
  ImprovementProposal,
  CompetitiveLandscape,
  BusinessModelProfile,
} from '@cs/domain';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'balam-licitaciones',
    name: 'BALAM Licitaciones',
    path: 'C:/dev/balam',
    stack: ['React', 'FastAPI', 'PostgreSQL', 'Vite'],
    maturity: 'developing',
    lastScanned: '2026-04-22T20:00:00Z',
    tags: ['b2b', 'procurement', 'ai'],
    description: 'Plataforma de inteligencia de mercado para licitaciones gubernamentales.',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-04-22T20:00:00Z',
  },
  {
    id: 'connected-strategy',
    name: 'Connected Strategy',
    path: 'C:/dev/Connected_Strategy',
    stack: ['React', 'Node.js', 'TypeScript', 'Electron'],
    maturity: 'nascent',
    lastScanned: '2026-04-22T21:54:00Z',
    tags: ['strategy', 'ai', 'local-first'],
    description: 'Torre de control estratégica para análisis multiproyecto.',
    createdAt: '2026-04-22T00:00:00Z',
    updatedAt: '2026-04-22T21:54:00Z',
  },
];

export const MOCK_METRICS: Record<string, StrategicMetrics> = {
  'balam-licitaciones': {
    projectId: 'balam-licitaciones',
    connectedExperienceScore: 68,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 80, curatedOffering: 65, coachBehavior: 60, automaticExecution: 55 }, formula: 'weighted avg', score: 68, rationale: 'Solid respond-to-desire but weak automatic execution' },
    closedLoopMaturity: 72,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 75, transmitCoverage: 70, analyzeDepth: 72, reactSpeed: 68 }, formula: 'weighted avg', score: 72, rationale: 'Good instrumentation, moderate reaction speed' },
    switchingCostIndex: 61,
    switchingCostBreakdown: { inputs: { dataLock: 70, habitFormation: 65, integrationDepth: 55, networkEffect: 45 }, formula: 'weighted avg', score: 61, rationale: 'Data lock strong, network effects weak' },
    wtpUpliftIndex: 74,
    wtpUpliftBreakdown: { inputs: { valuePerception: 78, painResolution: 72, convenienceDelta: 70 }, formula: 'weighted avg', score: 74, rationale: 'Clear value, good pain resolution' },
    costReductionPotential: 58,
    costReductionBreakdown: { inputs: { automationCoverage: 62, manualOpsReduction: 55, supportBurdenReduction: 55 }, formula: 'weighted avg', score: 58, rationale: 'Partial automation coverage' },
    competitivePositioningIndex: 65,
    competitivePositioningBreakdown: { inputs: { internalFit: 68, externalFit: 65, dynamicFit: 60, differentiationClarity: 65 }, formula: 'weighted avg', score: 65, rationale: 'Moderate competitive position' },
    businessModelStrength: 70,
    businessModelBreakdown: { inputs: { revenueModelClarity: 75, moatDepth: 65, scalability: 70, customerRelationshipDepth: 68 }, formula: 'weighted avg', score: 70, rationale: 'Clear revenue model, moderate moat' },
    dataScienceReadiness: 55,
    dataScienceBreakdown: { inputs: { dataAvailability: 60, instrumentationCoverage: 58, modelingCapability: 50, rigorLevel: 48 }, formula: 'weighted avg', score: 55, rationale: 'Data available but modeling early stage' },
    architectureResilience: 62,
    architectureResilienceBreakdown: { inputs: { modularity: 65, testCoverage: 55, observability: 65, recoverability: 60 }, formula: 'weighted avg', score: 62, rationale: 'Moderate test coverage' },
    strategicAdvantageComposite: 66,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 66, rationale: 'Above average strategic position' },
    calculatedAt: '2026-04-22T20:00:00Z',
    calculationVersion: '1.0.0',
  },
  'connected-strategy': {
    projectId: 'connected-strategy',
    connectedExperienceScore: 45,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 50, curatedOffering: 45, coachBehavior: 40, automaticExecution: 45 }, formula: 'weighted avg', score: 45, rationale: 'Early stage — foundation being built' },
    closedLoopMaturity: 38,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 40, transmitCoverage: 35, analyzeDepth: 40, reactSpeed: 35 }, formula: 'weighted avg', score: 38, rationale: 'Loop infrastructure being built' },
    switchingCostIndex: 30,
    switchingCostBreakdown: { inputs: { dataLock: 30, habitFormation: 25, integrationDepth: 35, networkEffect: 20 }, formula: 'weighted avg', score: 30, rationale: 'Early stage, low switching costs yet' },
    wtpUpliftIndex: 55,
    wtpUpliftBreakdown: { inputs: { valuePerception: 60, painResolution: 55, convenienceDelta: 48 }, formula: 'weighted avg', score: 55, rationale: 'Clear WTP hypothesis' },
    costReductionPotential: 70,
    costReductionBreakdown: { inputs: { automationCoverage: 75, manualOpsReduction: 70, supportBurdenReduction: 62 }, formula: 'weighted avg', score: 70, rationale: 'Strong automation potential' },
    competitivePositioningIndex: 50,
    competitivePositioningBreakdown: { inputs: { internalFit: 55, externalFit: 50, dynamicFit: 48, differentiationClarity: 45 }, formula: 'weighted avg', score: 50, rationale: 'Differentiation being established' },
    businessModelStrength: 42,
    businessModelBreakdown: { inputs: { revenueModelClarity: 40, moatDepth: 45, scalability: 45, customerRelationshipDepth: 38 }, formula: 'weighted avg', score: 42, rationale: 'Revenue model being validated' },
    dataScienceReadiness: 48,
    dataScienceBreakdown: { inputs: { dataAvailability: 50, instrumentationCoverage: 50, modelingCapability: 45, rigorLevel: 45 }, formula: 'weighted avg', score: 48, rationale: 'Scaffolded, readiness growing' },
    architectureResilience: 72,
    architectureResilienceBreakdown: { inputs: { modularity: 80, testCoverage: 65, observability: 70, recoverability: 72 }, formula: 'weighted avg', score: 72, rationale: 'Solid monorepo, good modularity' },
    strategicAdvantageComposite: 50,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 50, rationale: 'Nascent — high potential' },
    calculatedAt: '2026-04-22T21:54:00Z',
    calculationVersion: '1.0.0',
  },
};

export const MOCK_PROPOSALS: ImprovementProposal[] = [
  {
    id: 'prop-001',
    projectId: 'balam-licitaciones',
    title: 'Implementar pipeline de análisis semántico con embeddings',
    context: 'Las licitaciones se analizan con búsqueda de texto exacto. El matching semántico mejoraría el recall en ~40%.',
    evidence: ['búsqueda actual falla para sinónimos legales', 'competidores usan RAG embeddings'],
    expectedImpact: 'Aumenta cobertura de matching de 60% a ~85%. Sube WTP percibido.',
    risk: 'Costo de embeddings API si volumen crece. Requiere modelo de calidad.',
    riskLevel: 'medium',
    acceptanceCriteria: ['Recall@10 > 0.85 en test set', 'Costo < $0.02/búsqueda'],
    changeType: 'architecture',
    affectedComponents: ['search-engine', 'ingestion-pipeline'],
    strategicMapping: {
      raisesWTP: true,
      reducesCost: false,
      increasesSwitchingCosts: true,
      improvesActivitySystem: true,
      strengthensBusinessModel: true,
      senseTransmitPhase: 'Analyze',
      recognizeRequestPhase: 'Respond',
    },
    status: 'approved',
    requiresHumanApproval: false,
    createdAt: '2026-04-20T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
  },
  {
    id: 'prop-002',
    projectId: 'balam-licitaciones',
    title: 'Sistema de alertas proactivas por sector y monto',
    context: 'Usuarios deben revisar manualmente. Alertas automáticas reducirían esfuerzo y aumentarían retención.',
    evidence: ['NPS bajo en "descubrimiento de oportunidades"', 'feature request #1 en feedback'],
    expectedImpact: 'Coach-behavior activado. Reduce abandono en -25%. Aumenta DAU.',
    risk: 'Notificaciones mal calibradas = spam = churn.',
    riskLevel: 'low',
    acceptanceCriteria: ['Opt-out < 10%', 'CTR alertas > 30%'],
    changeType: 'feature',
    affectedComponents: ['notification-service', 'user-preferences'],
    strategicMapping: {
      raisesWTP: true,
      reducesCost: false,
      increasesSwitchingCosts: true,
      improvesActivitySystem: false,
      strengthensBusinessModel: false,
      senseTransmitPhase: 'React',
      recognizeRequestPhase: 'Respond',
    },
    status: 'draft',
    requiresHumanApproval: true,
    createdAt: '2026-04-21T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
  },
  {
    id: 'prop-003',
    projectId: 'balam-licitaciones',
    title: 'Módulo de análisis causal: correlación vs causalidad en tendencias',
    context: 'Los dashboards muestran correlaciones sin distinguir causalidad. Riesgo de decisiones erróneas.',
    evidence: ['MITx DS rigor standards', 'usuario tomó decisión basada en correlación espuria'],
    expectedImpact: 'Reduce riesgo decisional. Sube posicionamiento competitivo como plataforma de rigor analítico.',
    risk: 'Alto esfuerzo. Requiere estadístico/data scientist senior.',
    riskLevel: 'high',
    acceptanceCriteria: ['Al menos 3 análisis causales validados en producción'],
    changeType: 'data',
    affectedComponents: ['analytics-engine', 'dashboard-reports'],
    strategicMapping: {
      raisesWTP: true,
      reducesCost: false,
      increasesSwitchingCosts: true,
      improvesActivitySystem: true,
      strengthensBusinessModel: true,
      senseTransmitPhase: 'Analyze',
      recognizeRequestPhase: 'Recognize',
    },
    status: 'draft',
    requiresHumanApproval: true,
    createdAt: '2026-04-22T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
  },
];

export const MOCK_LANDSCAPE: CompetitiveLandscape = {
  projectId: 'balam-licitaciones',
  competitors: [
    { id: 'c1', name: 'CompraNet MX', strengths: ['volumen', 'oficial'], weaknesses: ['UX pobre', 'sin análisis'], wtpPosition: 'lower', costPosition: 'lower', switchingCostLevel: 'low', updatedAt: '2026-04-22T00:00:00Z' },
    { id: 'c2', name: 'Mercado Público CL', strengths: ['integración gobierno', 'API'], weaknesses: ['solo Chile', 'sin IA'], wtpPosition: 'similar', costPosition: 'similar', switchingCostLevel: 'medium', updatedAt: '2026-04-22T00:00:00Z' },
    { id: 'c3', name: 'Probol BO', strengths: ['precio', 'soporte'], weaknesses: ['sin ML', 'sin embeddings'], wtpPosition: 'lower', costPosition: 'lower', switchingCostLevel: 'low', updatedAt: '2026-04-22T00:00:00Z' },
  ],
  internalFit: 'Alto — pipeline de ingesta + RAG + dashboards se refuerzan mutuamente',
  externalFit: 'Moderado — WTP claro para analistas, menos para distribuidores nuevos',
  dynamicFit: 'Moderado — arquitectura local-first permite evolución rápida',
  activitySystem: [
    { id: 'as1', label: 'Ingesta automatizada', description: 'Conectores multiportal que alimentan el índice', isCore: true, reinforces: ['as2', 'as3'] },
    { id: 'as2', label: 'RAG + Embeddings', description: 'Matching semántico sobre corpus legal', isCore: true, reinforces: ['as3', 'as4'] },
    { id: 'as3', label: 'Alertas proactivas', description: 'Coach-behavior por sector y monto', isCore: false, reinforces: ['as4'] },
    { id: 'as4', label: 'Pipeline de partners', description: 'Gestión de relaciones con proveedores', isCore: false, reinforces: ['as1'] },
  ],
  wtpNarrative: 'Usuarios pagan por reducir tiempo de búsqueda y aumentar hit-rate en licitaciones relevantes.',
  costNarrative: 'Automatización de ingesta reduce costo marginal. Escala sin crecimiento proporcional de equipo.',
  differentiationChoices: ['Cobertura multi-país LATAM', 'Análisis semántico vs keyword', 'Local-first con AI'],
  convergenceRisks: ['Portales oficiales añadiendo analytics', 'GPT wrappers genéricos de búsqueda'],
  updatedAt: '2026-04-22T00:00:00Z',
};

export const MOCK_BM: BusinessModelProfile = {
  projectId: 'balam-licitaciones',
  valueProposition: 'Inteligencia de mercado de licitaciones LATAM: más oportunidades, menos tiempo, mejor decisión.',
  targetCustomerSegments: ['Fabricantes OEM LATAM', 'Distribuidores de equipos', 'Analistas de compras gubernamentales'],
  revenueStreams: ['SaaS mensual por rol', 'API access para enterprise', 'Reportes custom'],
  costStructure: ['Ingesta automatizada (low marginal)', 'AI API (usage-based)', 'Soporte (low-touch)'],
  keyResources: ['Corpus legal multi-país', 'Modelo de embeddings fine-tuned', 'Network de usuarios verificados'],
  keyActivities: ['Ingesta y normalización diaria', 'Mejora continua de RAG', 'Onboarding de nuevos portales'],
  keyPartners: ['Portales gubernamentales (data feed)', 'Proveedores de LLM', 'Integradores enterprise'],
  channels: ['Direct (demo → trial)', 'Partnerships con cámaras de comercio', 'Content SEO técnico'],
  customerRelationships: ['Self-serve onboarding', 'Success manager para enterprise', 'Comunidad de analistas'],
  connectedStrategyType: 'coach-behavior',
  moatSources: ['Corpus multi-país exclusivo', 'Embeddings entrenados en dominio legal', 'Network effects en pipeline'],
  activitySystem: [],
  updatedAt: '2026-04-22T00:00:00Z',
};
