/**
 * Mock data for UI development while backend (SET-03) is being built.
 * All types come from @cs/domain.
 */
import type {
  Project,
  ProjectSkill,
  ProjectWorkflow,
  ServiceAccess,
  StrategicMetrics,
  ImprovementProposal,
  CompetitiveLandscape,
  BusinessModelProfile,
} from '@cs/domain';

// ─── Global Antigravity Skills (scanned 2026-04-27) ───────────────────────────
const GLOBAL_SKILLS: ProjectSkill[] = [
  { name: 'brainstorming',              scope: 'global', category: 'ai-coding',    description: 'Explorar intent y requisitos antes de implementar' },
  { name: 'connected-strategy',         scope: 'global', category: 'analysis',     description: 'Pipeline local de análisis Connected Strategy sin API credits' },
  { name: 'dispatching-parallel-agents',scope: 'global', category: 'ai-coding',    description: 'Ejecutar 2+ tareas independientes en paralelo' },
  { name: 'executing-plans',            scope: 'global', category: 'dev-workflow',  description: 'Ejecutar planes escritos con review checkpoints' },
  { name: 'finishing-a-development-branch', scope:'global', category:'dev-workflow', description:'Guía de merge/PR al completar una rama' },
  { name: 'receiving-code-review',      scope: 'global', category: 'dev-workflow',  description: 'Procesar feedback de code review con rigor técnico' },
  { name: 'requesting-code-review',     scope: 'global', category: 'dev-workflow',  description: 'Verificar trabajo antes de hacer merge' },
  { name: 'subagent-driven-development',scope: 'global', category: 'ai-coding',    description: 'Ejecutar planes con sub-agentes en sesión actual' },
  { name: 'systematic-debugging',       scope: 'global', category: 'ai-coding',    description: 'Diagnóstico estructurado de bugs antes de proponer fixes' },
  { name: 'test-driven-development',    scope: 'global', category: 'dev-workflow',  description: 'Escribir tests antes de código de implementación' },
  { name: 'using-git-worktrees',        scope: 'global', category: 'dev-workflow',  description: 'Crear worktrees git aislados para feature work' },
  { name: 'using-superpowers',          scope: 'global', category: 'ai-coding',    description: 'Establecer cómo encontrar y usar skills al inicio de cada sesión' },
  { name: 'verification-before-completion', scope:'global', category:'dev-workflow', description:'Verificar con comandos reales antes de declarar éxito' },
  { name: 'writing-plans',              scope: 'global', category: 'dev-workflow',  description: 'Crear planes de implementación multi-step antes de tocar código' },
  { name: 'writing-skills',             scope: 'global', category: 'ai-coding',    description: 'Crear y editar skills para el sistema Antigravity' },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'balam-licitaciones',
    name: 'BALAM Licitaciones',
    path: 'C:/dev/antigravity-tenders-platform',
    stack: ['React', 'FastAPI', 'PostgreSQL', 'Python', 'ML'],
    maturity: 'developing',
    lastScanned: '2026-04-27T09:08:00Z',
    tags: ['b2b', 'procurement', 'ai', 'saas', 'ml', 'cloud-run'],
    description: 'Plataforma de inteligencia de mercado para licitaciones gubernamentales LATAM. V6 en PRODUCCIÓN: 1.96M rows, 17 portales, 5 modelos ML, Stripe billing.',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
    launcherScript: 'start.bat',
    healthUrl: 'https://balam-backend-422679037811.us-central1.run.app/health',
    scriptCount: 286,
    skills: [
      ...GLOBAL_SKILLS,
    ],
    workflows: [
      { name: 'BALAM Alert: Tender Change', file: 'BALAM_alert_tender_change.json', platform: 'n8n', status: 'active', description: 'Alerta cuando cambia el estado de una licitación seguida', triggers: ['webhook', 'cron'] },
      { name: 'BALAM CRM: Push Lead', file: 'BALAM_crm_push_lead.json', platform: 'n8n', status: 'active', description: 'Empuja leads de licitaciones ganadas al CRM', triggers: ['webhook'] },
      { name: 'LIC Cerebro Daemon', file: 'lic_cerebro_daemon.py', platform: 'daemon', status: 'active', description: 'Daemon 24/7: escanea 12 portales LATAM (3 slots API + 1 browser + 2 PDF). Ciclo: 60s', triggers: ['always-on'] },
      { name: 'GCloud Workflows API v1', file: 'workflows.v1.json', platform: 'script', status: 'unknown', description: 'Google Cloud Workflows API schema v1', triggers: [] },
      { name: 'GCloud Workflows API v1beta', file: 'workflows.v1beta.json', platform: 'script', status: 'unknown', description: 'Google Cloud Workflows API schema v1beta', triggers: [] },
    ],
  },
  {
    id: 'connected-strategy',
    name: 'Connected Strategy',
    path: 'C:/dev/Connected_Strategy',
    stack: ['React', 'Node.js', 'TypeScript', 'SQLite'],
    maturity: 'developing',
    lastScanned: '2026-04-27T09:08:00Z',
    tags: ['strategy', 'ai', 'local-first', 'control-tower', 'wharton'],
    description: 'Torre de control estratégica v2.2.0. 20 agentes swarm, 27 páginas, Coach Wharton proactivo, Causal DAG, Portfolio Matrix.',
    createdAt: '2026-04-22T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
    launcherScript: 'Connected Strategy.bat',
    healthUrl: 'http://127.0.0.1:4310/health',
    scriptCount: 0,
    skills: [
      ...GLOBAL_SKILLS,
      { name: 'connected-strategy-analysis', scope: 'local', category: 'analysis', description: 'Pipeline de análisis Wharton con 20 agentes jerárquicos (local)' },
    ],
    workflows: [],
  },
  {
    id: 'rodrigo-os',
    name: 'Rodrigo OS',
    path: 'C:/dev/rodrigo-os',
    stack: ['Python', 'GCP', 'PostgreSQL'],
    maturity: 'nascent',
    lastScanned: '2026-04-27T09:08:00Z',
    tags: ['personal-os', 'health', 'infra', 'gcp'],
    description: 'Control plane personal. Repositorio de definición (sin código ejecutable aún). AGENTS.md + GEMINI.md configurados.',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
    launcherScript: 'code',
    scriptCount: 0,
    skills: [...GLOBAL_SKILLS],
    workflows: [],
  },
  {
    id: 'rodrigo-os-health',
    name: 'Health Dashboard',
    path: 'C:/dev/rodrigo-os-health',
    stack: ['Python', 'HTML', 'PostgreSQL', 'GCP', 'n8n'],
    maturity: 'nascent',
    lastScanned: '2026-04-27T09:08:00Z',
    tags: ['health', 'data', 'dashboard', 'n8n', 'gcp'],
    description: '18 archivos Python, datos de salud longitudinal. 5 workflows n8n activos (Supervisor, Daily Briefing, Email Triage, Health Monitor, Moltbot Bridge).',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
    launcherScript: 'run_dashboard.bat',
    healthUrl: 'http://localhost:5050',
    scriptCount: 18,
    skills: [...GLOBAL_SKILLS],
    workflows: [
      { name: 'Supervisor Main', file: '00-supervisor-main.json', platform: 'n8n', status: 'active', description: 'Agente supervisor R — coordina todos los workflows de salud', triggers: ['manual', 'webhook'] },
      { name: 'Daily Briefing', file: '01-daily-briefing.json', platform: 'n8n', status: 'active', description: 'Resumen diario de métricas de salud y agenda', triggers: ['cron:06:00'] },
      { name: 'Email Triage', file: '02-email-triage.json', platform: 'n8n', status: 'active', description: 'Clasifica y prioriza emails entrantes automáticamente', triggers: ['cron:*/15min'] },
      { name: 'Health Monitor', file: '03-health-monitor.json', platform: 'n8n', status: 'active', description: 'Monitorea métricas de salud y dispara alertas', triggers: ['cron:hourly'] },
      { name: 'Moltbot Bridge', file: '04-moltbot-bridge.json', platform: 'n8n', status: 'active', description: 'Bridge al bot de Telegram para notificaciones', triggers: ['webhook'] },
    ],
    serviceAccess: [
      {
        name: 'n8n Instance — GCP e2-micro',
        url: 'http://34.30.64.33:5678/home/workflows',
        platform: 'n8n',
        status: 'unknown',
        credentialHint: {
          user: 'rperus@sklatam.org',
          passwordHint: 'B_****',
          note: 'Instancia n8n en GCP e2-micro. Workflows: Supervisor, Daily Briefing, Email Triage, Health Monitor, Moltbot Bridge.',
        },
      },
    ],
  },
  {
    id: 'youtube-cashcow',
    name: 'YouTube CashCow',
    path: 'C:/dev/youtube-cashcow',
    stack: ['Python', 'n8n', 'JavaScript', 'AI', 'ML'],
    maturity: 'nascent',
    lastScanned: '2026-04-27T09:08:00Z',
    tags: ['youtube', 'automation', 'content', 'cashcow', 'n8n', 'ml'],
    description: '35+ archivos Python (agentic_swarm, autonomous_video_engine, factory_boss, ds_core, ds_outliers) + 4 n8n workflows. Pipeline automático de creación, ensamble y publicación de videos YouTube.',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
    launcherScript: 'CashCow_Dashboard.bat',
    scriptCount: 35,
    skills: [...GLOBAL_SKILLS],
    workflows: [
      { name: 'Master Pipeline', file: 'n8n_master_pipeline.json', platform: 'n8n', status: 'unknown', description: 'Pipeline maestro de producción de videos', triggers: ['cron', 'manual'] },
      { name: 'CASHCOW Master Radar', file: 'CASHCOW_Master_Radar.json', platform: 'n8n', status: 'unknown', description: 'Radar de tendencias y oportunidades de contenido', triggers: ['cron:daily'] },
      { name: 'CASHCOW Generador de Voz', file: 'CASHCOW_Generador_Voz.json', platform: 'n8n', status: 'unknown', description: 'Generación de voz para videos', triggers: ['webhook'] },
      { name: '01 RADAR Workflow', file: '01_RADAR_WORKFLOW.json', platform: 'n8n', status: 'unknown', description: 'Workflow de radar de contenido v1', triggers: ['cron'] },
    ],
  },
  {
    id: 'balam-demo',
    name: 'BALAM Demo',
    path: 'C:/dev/balam-demo-v2',
    stack: ['React', 'TypeScript', 'Node.js', 'Python'],
    maturity: 'developing',
    lastScanned: '2026-04-27T09:08:00Z',
    tags: ['demo', 'balam', 'ui', 'typescript'],
    description: '68 archivos TypeScript + 4 Python. 6 scripts (build_maps, export_evidence_pack, generate_mock_data). Demo visual de la plataforma BALAM.',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
    launcherScript: 'code',
    scriptCount: 6,
    skills: [...GLOBAL_SKILLS],
    workflows: [],
  },
  {
    id: 'grant-navigator',
    name: 'Grant Navigator',
    path: 'C:/dev/Grant-Navigator',
    stack: ['Python', 'AI', 'Docs'],
    maturity: 'nascent',
    lastScanned: '2026-04-27T09:08:00Z',
    tags: ['grants', 'ai', 'research', 'business-plan', 'caf', 'solarkey'],
    description: 'Repositorio de documentos estratégicos: Business Plans BALAM Nexus (v2-v5), pitch decks CAF/DFI, Project Mariner playbooks (30K+ tokens de prompts de grants), SolarKey LLC canvas. 1 script Python (build_solarkey_docs.py).',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
    launcherScript: 'code',
    scriptCount: 1,
    skills: [...GLOBAL_SKILLS],
    workflows: [],
    serviceAccess: [],
  },
];

export const MOCK_METRICS: Record<string, StrategicMetrics> = {
  // BALAM Licitaciones — Evidence: v6.6 production, 573/573 tests, GCP Cloud Run,
  // 762K canonical records, 57 portals/25 countries, 5-model ML pipeline (AUC-ROC=0.72),
  // Stripe billing (Free+Pro $49/mo), LinkedIn+Google OAuth, 35 products PIM catalog.
  // Wharton assessment: Strongest platform in portfolio — real production, real revenue model.
  'balam-licitaciones': {
    projectId: 'balam-licitaciones',
    // Respond-to-desire: 762K records + semantic search = excellent. Curated: AI classifier.
    // Coach: alert system (prop-002 in draft). Automatic: human still approves proposals.
    connectedExperienceScore: 72,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 88, curatedOffering: 75, coachBehavior: 58, automaticExecution: 45 }, formula: 'weighted avg', score: 72, rationale: 'Excellent respond-to-desire (real-time semantic matching on 762K records). Strong curated offering via AI classifier. Coach behavior in progress (sector alerts). Automatic execution blocked — human must approve every proposal.' },
    // Sense: 57 portals, 66.6GB raw, LIC Cerebro daemon. Transmit: Cloud SQL + vector index.
    // Analyze: TF-IDF+BM25+SBERT+XGBoost (AUC-ROC=0.72). React: proposals auto-generated.
    closedLoopMaturity: 78,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 85, transmitCoverage: 80, analyzeDepth: 78, reactSpeed: 68 }, formula: 'weighted avg', score: 78, rationale: 'Outstanding sense quality (57 portals, daily daemon, 66.6GB). Strong transmission to Cloud SQL. Deep analysis via 5-model ML stack. React speed limited by human approval gates on proposals.' },
    // Data lock: 762K records + saved portal credentials. Habit: daily tender alerts.
    // Integration: API access + Stripe. Network: portal improvements benefit all users.
    switchingCostIndex: 68,
    switchingCostBreakdown: { inputs: { dataLock: 78, habitFormation: 70, integrationDepth: 65, networkEffect: 55 }, formula: 'weighted avg', score: 68, rationale: 'Strong data lock: 762K canonical records + org-scoped product libraries + saved portal credentials. Habit formation via daily alerts. Network effect: shared portal coverage improvements benefit entire user base (population learning).' },
    // Pain: manual search across 57 portals = 4-8h/week per analyst. Very high WTP.
    // Value perception: one-click proposal generation with 7-section tech spec.
    wtpUpliftIndex: 82,
    wtpUpliftBreakdown: { inputs: { valuePerception: 88, painResolution: 85, convenienceDelta: 72 }, formula: 'weighted avg', score: 82, rationale: 'Highest WTP in portfolio. Pain resolution: eliminates 4-8h/week of manual tender search. Value perception: B2G sales teams pay for hit-rate. Convenience: auto-generated proposals with 7 technical sections.' },
    // Automation: 57-portal daemon + serverless GCP pipeline. ML runs continuously.
    costReductionPotential: 72,
    costReductionBreakdown: { inputs: { automationCoverage: 78, manualOpsReduction: 72, supportBurdenReduction: 65 }, formula: 'weighted avg', score: 72, rationale: 'High automation coverage: LIC Cerebro daemon, serverless ML pipeline, automated ingestion. Manual ops reduced significantly. Support burden low via self-serve Stripe billing.' },
    // Internal fit: ingestion→embeddings→dashboards→alerts all self-reinforcing.
    // Differentiation: only multi-country LATAM platform with ML matching.
    competitivePositioningIndex: 76,
    competitivePositioningBreakdown: { inputs: { internalFit: 82, externalFit: 75, dynamicFit: 70, differentiationClarity: 78 }, formula: 'weighted avg', score: 76, rationale: 'Strong internal activity system fit. Clear differentiation vs CompraNet (no AI), MercadoPublico (single country), Probol (no ML). Only LATAM platform with 57 portals + semantic ML matching.' },
    // Stripe TEST mode live. Free→Pro $49/mo. API for enterprise. GCP scales to zero.
    businessModelStrength: 75,
    businessModelBreakdown: { inputs: { revenueModelClarity: 82, moatDepth: 72, scalability: 78, customerRelationshipDepth: 68 }, formula: 'weighted avg', score: 75, rationale: 'Clear SaaS model: Stripe billing operational (Free+Pro $49/mo). API upsell path. Moat: 66.6GB proprietary corpus + fine-tuned ML models. GCP Cloud Run scales to zero cost. Org-scoped product libraries create B2B switching costs.' },
    // 762K records, 12.9M Colombia SECOP II. 5-model ML stack. AUC-ROC=0.72.
    dataScienceReadiness: 78,
    dataScienceBreakdown: { inputs: { dataAvailability: 88, instrumentationCoverage: 78, modelingCapability: 75, rigorLevel: 72 }, formula: 'weighted avg', score: 78, rationale: 'Best data position in portfolio: 762K parsed + 12.9M SECOP II. 5-model ML pipeline (AUC-ROC=0.72). 573 automated tests include ML benchmarks. Gap: causal inference layer missing.' },
    // 573/573 tests. TypeScript clean. GCP Cloud Run + Cloud SQL Auth Proxy. Pre-flight mandatory.
    architectureResilience: 80,
    architectureResilienceBreakdown: { inputs: { modularity: 82, testCoverage: 85, observability: 78, recoverability: 78 }, formula: 'weighted avg', score: 80, rationale: '573/573 tests. TypeScript + Python typed. GCP Cloud Run (auto-healing). Cloud SQL Auth Proxy (no public access). Mandatory preflight_check.py before every commit. Layered architecture: FastAPI + React + independent ML scripts.' },
    strategicAdvantageComposite: 76,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 76, rationale: 'Strongest platform in portfolio. Production-grade B2G intelligence with real revenue. Primary gaps: automatic execution requires human approval, coach behavior alerts in draft, Stripe still in TEST mode.' },
    calculatedAt: '2026-04-27T04:00:00Z',
    calculationVersion: '2.0.0',
  },
  // Connected Strategy — Evidence: This platform itself. 22 pages, 15 worksheets, 12 agents,
  // TypeScript monorepo (pnpm), SQLite persistence, Vite+React frontend, Express backend.
  // Wharton self-assessment: Strong architecture, weak on market fit (internal tool, no revenue).
  // Connected experience: responds to strategic queries (worksheets) but no proactive coaching.
  'connected-strategy': {
    projectId: 'connected-strategy',
    connectedExperienceScore: 48,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 62, curatedOffering: 48, coachBehavior: 38, automaticExecution: 42 }, formula: 'weighted avg', score: 48, rationale: 'Responds to strategic queries via worksheets (respond-to-desire). Agent pipeline auto-fills analysis (curated). No proactive coaching or automatic execution for user decisions.' },
    closedLoopMaturity: 55,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 58, transmitCoverage: 55, analyzeDepth: 60, reactSpeed: 48 }, formula: 'weighted avg', score: 55, rationale: 'Senses portfolio via scanner agent. Transmits to SQLite. 12-agent analysis pipeline. React: proposal composer generates output but user must act manually.' },
    switchingCostIndex: 42,
    switchingCostBreakdown: { inputs: { dataLock: 55, habitFormation: 38, integrationDepth: 42, networkEffect: 20 }, formula: 'weighted avg', score: 42, rationale: 'Worksheet data stored in SQLite creates moderate lock-in. Habit forming (daily strategy review). No network effects — single-user tool.' },
    wtpUpliftIndex: 58,
    wtpUpliftBreakdown: { inputs: { valuePerception: 65, painResolution: 58, convenienceDelta: 50 }, formula: 'weighted avg', score: 58, rationale: 'Clear strategic value for multi-project founders. Pain: context-switching between 7 projects without a unified view. Convenience: one-click analysis pipeline.' },
    costReductionPotential: 72,
    costReductionBreakdown: { inputs: { automationCoverage: 78, manualOpsReduction: 72, supportBurdenReduction: 65 }, formula: 'weighted avg', score: 72, rationale: 'Strong automation: 12-agent pipeline replaces 8+ hours of manual analysis per project. No human needed for initial scoring. Self-reinforcing via auto-fill + scoring.' },
    competitivePositioningIndex: 52,
    competitivePositioningBreakdown: { inputs: { internalFit: 65, externalFit: 45, dynamicFit: 55, differentiationClarity: 45 }, formula: 'weighted avg', score: 52, rationale: 'Strong internal fit (worksheets feed agents feed proposals). Weak external fit — no market validation yet. Differentiation: Wharton curriculum alignment is unique but unproven commercially.' },
    businessModelStrength: 35,
    businessModelBreakdown: { inputs: { revenueModelClarity: 25, moatDepth: 45, scalability: 40, customerRelationshipDepth: 28 }, formula: 'weighted avg', score: 35, rationale: 'No revenue model — internal tool. Moat: proprietary Wharton-aligned scoring engine. Could pivot to SaaS (founder strategy tool). Scalability: local-first limits reach.' },
    dataScienceReadiness: 55,
    dataScienceBreakdown: { inputs: { dataAvailability: 52, instrumentationCoverage: 58, modelingCapability: 55, rigorLevel: 55 }, formula: 'weighted avg', score: 55, rationale: 'Deterministic scoring engine (not ML). 15 worksheets create structured data. Agent pipeline produces typed findings. Gap: no statistical modeling or longitudinal trend analysis.' },
    architectureResilience: 75,
    architectureResilienceBreakdown: { inputs: { modularity: 82, testCoverage: 65, observability: 72, recoverability: 78 }, formula: 'weighted avg', score: 75, rationale: 'Excellent modularity: pnpm monorepo, @cs/domain, @cs/agents, @cs/web all typed. TypeScript strict. SQLite with fallback to localStorage. ErrorBoundary. Gap: limited automated test coverage.' },
    strategicAdvantageComposite: 55,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 55, rationale: 'Strong technical foundation. Best internal-tool architecture in portfolio. Needs revenue model and external validation to become commercially viable.' },
    calculatedAt: '2026-04-27T04:00:00Z',
    calculationVersion: '2.0.0',
  },
  // Rodrigo OS — Evidence: Governance control plane only. No product code.
  // STATUS.md: Phase 1 Health Data Foundation. GCP infra provisioned.
  // This is a meta-repo that PLANS and coordinates — not the actual product.
  'rodrigo-os': {
    projectId: 'rodrigo-os',
    connectedExperienceScore: 25,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 30, curatedOffering: 20, coachBehavior: 25, automaticExecution: 20 }, formula: 'weighted avg', score: 25, rationale: 'Governance repo, not a product. Contains plans and ADRs but no user-facing connected experience. Codex+Antigravity model is respond-to-desire for the developer, not an end customer.' },
    closedLoopMaturity: 22,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 25, transmitCoverage: 18, analyzeDepth: 25, reactSpeed: 20 }, formula: 'weighted avg', score: 22, rationale: 'No automated sensing pipeline in this repo. Plans are written, not executed here. Actual execution happens in rodrigo-os-health workspace.' },
    switchingCostIndex: 40,
    switchingCostBreakdown: { inputs: { dataLock: 55, habitFormation: 38, integrationDepth: 35, networkEffect: 18 }, formula: 'weighted avg', score: 40, rationale: 'Personal data (health, infra inventory) creates inherent lock-in. GCP infra inventory in YAML. ADR decisions accumulate institutional memory.' },
    wtpUpliftIndex: 55,
    wtpUpliftBreakdown: { inputs: { valuePerception: 62, painResolution: 55, convenienceDelta: 45 }, formula: 'weighted avg', score: 55, rationale: 'High personal value: unified governance across health, infra, phases of life. Pain resolved: context chaos when switching between personal projects.' },
    costReductionPotential: 48,
    costReductionBreakdown: { inputs: { automationCoverage: 42, manualOpsReduction: 55, supportBurdenReduction: 45 }, formula: 'weighted avg', score: 48, rationale: 'Structured packet system reduces cognitive overhead. n8n automations planned for Phase 2+ reduce manual tasks.' },
    competitivePositioningIndex: 20,
    competitivePositioningBreakdown: { inputs: { internalFit: 28, externalFit: 15, dynamicFit: 20, differentiationClarity: 18 }, formula: 'weighted avg', score: 20, rationale: 'Personal tool, no market. Internal fit developing as sub-repos mature.' },
    businessModelStrength: 18,
    businessModelBreakdown: { inputs: { revenueModelClarity: 10, moatDepth: 28, scalability: 12, customerRelationshipDepth: 22 }, formula: 'weighted avg', score: 18, rationale: 'No revenue model intended. Personal OS. Moat: accumulated personal data + GCP infra knowledge.' },
    dataScienceReadiness: 32,
    dataScienceBreakdown: { inputs: { dataAvailability: 38, instrumentationCoverage: 30, modelingCapability: 28, rigorLevel: 30 }, formula: 'weighted avg', score: 32, rationale: 'GCP infra + health data exists in sub-repos. This governance repo has no pipeline itself.' },
    architectureResilience: 42,
    architectureResilienceBreakdown: { inputs: { modularity: 48, testCoverage: 25, observability: 45, recoverability: 48 }, formula: 'weighted avg', score: 42, rationale: 'Well-structured governance documents. GCP infra documented in YAML. No automated tests (docs repo).' },
    strategicAdvantageComposite: 32,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 32, rationale: 'Governance control plane. Value comes from coordination, not execution. Real strategic value appears when sub-repos (health, n8n, voice) mature.' },
    calculatedAt: '2026-04-27T04:00:00Z',
    calculationVersion: '2.0.0',
  },
  // Health Dashboard — Evidence: Python+PostgreSQL (GCP Cloud SQL), 8 API endpoints,
  // dashboard live at localhost:5050, 21 real lab studies (2014-2026),
  // 14 medication records, 6 aesthetic procedures, CSV import from Fitdays/Withings.
  // AG-012 delivered. Chat+upload integrated (AG-013). AG-020 email integration planned.
  'rodrigo-os-health': {
    projectId: 'rodrigo-os-health',
    // Real dashboard serving real data. Responds to health queries. No automated coaching.
    connectedExperienceScore: 45,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 60, curatedOffering: 42, coachBehavior: 38, automaticExecution: 28 }, formula: 'weighted avg', score: 45, rationale: 'Dashboard responds to health data queries (8 real API endpoints). Chat intake (AG-013) adds request channel. No proactive coaching or automatic treatment recommendations yet.' },
    // Sense: CSV import + manual entry. Transmit: Cloud SQL. Analyze: manual interpretation.
    closedLoopMaturity: 38,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 52, transmitCoverage: 38, analyzeDepth: 35, reactSpeed: 25 }, formula: 'weighted avg', score: 38, rationale: 'Sensing via CSV import (Fitdays/Withings) + manual entry. Cloud SQL transmission reliable. Analysis is manual — physician interprets. React: no automated health alerts yet.' },
    // Irreplaceable 12-year longitudinal dataset is the ultimate data lock.
    switchingCostIndex: 62,
    switchingCostBreakdown: { inputs: { dataLock: 85, habitFormation: 55, integrationDepth: 45, networkEffect: 12 }, formula: 'weighted avg', score: 62, rationale: 'Extremely strong data lock: 12-year longitudinal health record (2014-2026), 21 lab studies, medication history. This data cannot be recreated. Habit: daily health check routine building.' },
    // Health visibility is one of the highest-WTP personal use cases possible.
    wtpUpliftIndex: 75,
    wtpUpliftBreakdown: { inputs: { valuePerception: 82, painResolution: 75, convenienceDelta: 65 }, formula: 'weighted avg', score: 75, rationale: 'Very high WTP: centralized view of 12 years of health data resolves massive pain (scattered lab PDFs, appointment notes, medication lists). Convenience: one dashboard vs multiple providers.' },
    costReductionPotential: 42,
    costReductionBreakdown: { inputs: { automationCoverage: 38, manualOpsReduction: 48, supportBurdenReduction: 38 }, formula: 'weighted avg', score: 42, rationale: 'CSV import automates some data entry. Manual entry still required for new records. Future: AG-020 email integration will automate lab result ingestion.' },
    competitivePositioningIndex: 22,
    competitivePositioningBreakdown: { inputs: { internalFit: 28, externalFit: 18, dynamicFit: 22, differentiationClarity: 20 }, formula: 'weighted avg', score: 22, rationale: 'Personal tool — no market. Differentiation is irrelevant here. Value is entirely personal.' },
    businessModelStrength: 15,
    businessModelBreakdown: { inputs: { revenueModelClarity: 8, moatDepth: 22, scalability: 10, customerRelationshipDepth: 20 }, formula: 'weighted avg', score: 15, rationale: 'No revenue model. Pure personal health infrastructure. Could pivot to longevity SaaS but not intended.' },
    // Best data science position of personal projects: real longitudinal data with timestamps.
    dataScienceReadiness: 62,
    dataScienceBreakdown: { inputs: { dataAvailability: 78, instrumentationCoverage: 58, modelingCapability: 52, rigorLevel: 60 }, formula: 'weighted avg', score: 62, rationale: 'Best DS asset in personal portfolio: 12-year longitudinal health record. Real lab values with dates. Could support time-series analysis, biomarker trending, anomaly detection. Gap: no ML pipeline yet.' },
    architectureResilience: 45,
    architectureResilienceBreakdown: { inputs: { modularity: 45, testCoverage: 30, observability: 48, recoverability: 55 }, formula: 'weighted avg', score: 45, rationale: 'Python scripts + GCP Cloud SQL + HTML dashboard. Simple but functional. Recoverability good (Cloud SQL backups). Gap: no automated tests, monolithic scripts.' },
    strategicAdvantageComposite: 42,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 42, rationale: 'Highest personal value in portfolio. The 12-year health dataset is a genuinely unique asset. Strategic opportunity: add automated analysis and coaching to reach Trusted Partner status.' },
    calculatedAt: '2026-04-27T04:00:00Z',
    calculationVersion: '2.0.0',
  },
  // YouTube CashCow — Evidence: autonomous_video_engine.py, agentic_swarm.py,
  // cashcow-dashboard, n8n workflows, AI content pipeline. No user base yet.
  // High automation potential but no feedback loop from audience to content.
  'youtube-cashcow': {
    projectId: 'youtube-cashcow',
    connectedExperienceScore: 28,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 32, curatedOffering: 25, coachBehavior: 28, automaticExecution: 25 }, formula: 'weighted avg', score: 28, rationale: 'No audience-facing connected experience yet. Pipeline produces content but no feedback loop from viewer behavior to content decisions. No respond-to-desire for end viewers.' },
    closedLoopMaturity: 20,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 22, transmitCoverage: 18, analyzeDepth: 20, reactSpeed: 18 }, formula: 'weighted avg', score: 20, rationale: 'No closed loop: content is produced but no YouTube Analytics data feeds back into topic selection or style decisions. agentic_swarm.py runs forward, not circular.' },
    switchingCostIndex: 15,
    switchingCostBreakdown: { inputs: { dataLock: 18, habitFormation: 12, integrationDepth: 15, networkEffect: 12 }, formula: 'weighted avg', score: 15, rationale: 'Lowest switching costs in portfolio. Scripts can be copied or replaced. No proprietary dataset. No audience relationship built yet.' },
    wtpUpliftIndex: 62,
    wtpUpliftBreakdown: { inputs: { valuePerception: 68, painResolution: 62, convenienceDelta: 55 }, formula: 'weighted avg', score: 62, rationale: 'High value if it works: YouTube channel at scale generates passive income. Pain resolved: manually creating faceless videos takes 6-10h/video. Convenience: autonomous pipeline.' },
    costReductionPotential: 78,
    costReductionBreakdown: { inputs: { automationCoverage: 85, manualOpsReduction: 78, supportBurdenReduction: 70 }, formula: 'weighted avg', score: 78, rationale: 'Highest automation potential in portfolio. autonomous_video_engine.py + agentic_swarm.py + n8n reduce manual video production from 8h to near-zero. caar_autopilot.py adds continuous operation.' },
    competitivePositioningIndex: 30,
    competitivePositioningBreakdown: { inputs: { internalFit: 35, externalFit: 28, dynamicFit: 30, differentiationClarity: 28 }, formula: 'weighted avg', score: 30, rationale: 'Crowded space (many cashcow automation tools). Differentiation via AI quality + agentic autonomy. No moat until a channel reaches scale.' },
    businessModelStrength: 45,
    businessModelBreakdown: { inputs: { revenueModelClarity: 55, moatDepth: 32, scalability: 60, customerRelationshipDepth: 28 }, formula: 'weighted avg', score: 45, rationale: 'Clear monetization path: YouTube AdSense at scale. Scalability high (one pipeline, many channels possible). Moat weak until channel authority builds. No direct customer relationship (audience is passive).' },
    dataScienceReadiness: 28,
    dataScienceBreakdown: { inputs: { dataAvailability: 28, instrumentationCoverage: 25, modelingCapability: 30, rigorLevel: 28 }, formula: 'weighted avg', score: 28, rationale: 'No analytics pipeline reading YouTube data back into the system. Scripts generate content but do not learn from performance. Gap: YouTube Analytics API integration would close the loop.' },
    architectureResilience: 32,
    architectureResilienceBreakdown: { inputs: { modularity: 38, testCoverage: 18, observability: 35, recoverability: 38 }, formula: 'weighted avg', score: 32, rationale: 'Python scripts with some modularity (agents/, scripts/, config/). No automated tests. Observability limited to print logs. Recoverability depends on whether API keys are backed up.' },
    strategicAdvantageComposite: 35,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 35, rationale: 'High automation ceiling but no loop, no audience, no moat yet. Key risk: YouTube algorithm changes can destroy the model overnight. Strategic priority: integrate Analytics feedback loop to enable continuous improvement.' },
    calculatedAt: '2026-04-27T04:00:00Z',
    calculationVersion: '2.0.0',
  },
  // BALAM Demo — Evidence: Dual-track workspace: storytelling demo (root) + real platform scaffold.
  // apps/api (modular monolith), apps/web (ops shell), apps/mobile (Expo/RN), packages/domain.
  // More mature than the name suggests — real architectural foundation.
  'balam-demo': {
    projectId: 'balam-demo',
    connectedExperienceScore: 50,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 62, curatedOffering: 50, coachBehavior: 42, automaticExecution: 38 }, formula: 'weighted avg', score: 50, rationale: 'Demo storytelling app has respond-to-desire (user navigates product story). Real platform scaffold has API and web ops shell. Mobile app adds offline-first field capability (future).' },
    closedLoopMaturity: 42,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 48, transmitCoverage: 42, analyzeDepth: 40, reactSpeed: 38 }, formula: 'weighted avg', score: 42, rationale: 'Platform scaffold has API endpoints. Domain package has canonical BALAM entities. Loop is architectural but not yet operational — no live data flowing.' },
    switchingCostIndex: 38,
    switchingCostBreakdown: { inputs: { dataLock: 42, habitFormation: 35, integrationDepth: 40, networkEffect: 28 }, formula: 'weighted avg', score: 38, rationale: 'Domain package creates type contracts across web/mobile/API (moderate lock-in). RBAC helpers and seed data create organizational switching costs if adopted.' },
    wtpUpliftIndex: 60,
    wtpUpliftBreakdown: { inputs: { valuePerception: 68, painResolution: 58, convenienceDelta: 52 }, formula: 'weighted avg', score: 60, rationale: 'Demo converts prospects. Real platform addresses field operations pain (mobile offline-first). Clear value proposition for institutional buyers.' },
    costReductionPotential: 48,
    costReductionBreakdown: { inputs: { automationCoverage: 50, manualOpsReduction: 48, supportBurdenReduction: 45 }, formula: 'weighted avg', score: 48, rationale: 'Platform scaffold has test runner (pnpm run test:platform). Mobile field app reduces manual reporting. Moderate automation vs the main BALAM platform.' },
    competitivePositioningIndex: 55,
    competitivePositioningBreakdown: { inputs: { internalFit: 62, externalFit: 52, dynamicFit: 52, differentiationClarity: 55 }, formula: 'weighted avg', score: 55, rationale: 'Shares DNA and domain contracts with main Balam platform. Differentiation: mobile-first field operations + institutional web shell. Internal fit strong via packages/domain.' },
    businessModelStrength: 48,
    businessModelBreakdown: { inputs: { revenueModelClarity: 52, moatDepth: 45, scalability: 55, customerRelationshipDepth: 40 }, formula: 'weighted avg', score: 48, rationale: 'Demo-to-enterprise conversion model. Real platform has multi-role RBAC for institutional buyers. Mobile adds field operator tier. Scalability: React Native + modular API.' },
    dataScienceReadiness: 40,
    dataScienceBreakdown: { inputs: { dataAvailability: 42, instrumentationCoverage: 40, modelingCapability: 38, rigorLevel: 38 }, formula: 'weighted avg', score: 40, rationale: 'Domain package has canonical entities. No analytics pipeline yet. Seed data provides baseline. Gap: no ML or reporting layer.' },
    architectureResilience: 62,
    architectureResilienceBreakdown: { inputs: { modularity: 72, testCoverage: 52, observability: 58, recoverability: 65 }, formula: 'weighted avg', score: 62, rationale: 'Strong modularity: 5 packages (api, web, mobile, domain, design-system). pnpm workspace. BALAM UI governance contract. Test runner configured. Design system shared tokens.' },
    strategicAdvantageComposite: 50,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 50, rationale: 'Underrated platform. Not just a demo — real architectural foundation for institutional BALAM. Mobile-first field capability is a genuine differentiator. Needs data pipeline and live deployment to reach full potential.' },
    calculatedAt: '2026-04-27T04:00:00Z',
    calculationVersion: '2.0.0',
  },
  // Grant Navigator — Evidence: Only CSV files + PDF + business plan docs.
  // No runnable code. grant_navigator_master_funding_2026-04-09.csv exists.
  // Concept-stage: idea + research files, no product built yet.
  'grant-navigator': {
    projectId: 'grant-navigator',
    connectedExperienceScore: 15,
    connectedExperienceBreakdown: { inputs: { respondToDesire: 18, curatedOffering: 12, coachBehavior: 15, automaticExecution: 12 }, formula: 'weighted avg', score: 15, rationale: 'No product exists yet. Only research CSVs and business plan documents. Zero connected experience delivered to any user.' },
    closedLoopMaturity: 10,
    closedLoopMaturityBreakdown: { inputs: { senseQuality: 12, transmitCoverage: 8, analyzeDepth: 12, reactSpeed: 8 }, formula: 'weighted avg', score: 10, rationale: 'No sensing, no pipeline, no loop. CSV files represent manual research, not automated data acquisition.' },
    switchingCostIndex: 10,
    switchingCostBreakdown: { inputs: { dataLock: 15, habitFormation: 8, integrationDepth: 8, networkEffect: 5 }, formula: 'weighted avg', score: 10, rationale: 'No product to switch from. CSV is the only artifact and is fully portable.' },
    wtpUpliftIndex: 72,
    wtpUpliftBreakdown: { inputs: { valuePerception: 78, painResolution: 75, convenienceDelta: 62 }, formula: 'weighted avg', score: 72, rationale: 'Extremely high WTP potential: grant discovery and application is a massive pain for nonprofits, startups, and researchers. Manual search takes weeks. The PROBLEM has very high WTP even though no product exists.' },
    costReductionPotential: 70,
    costReductionBreakdown: { inputs: { automationCoverage: 75, manualOpsReduction: 70, supportBurdenReduction: 62 }, formula: 'weighted avg', score: 70, rationale: 'Opportunity score, not current state. AI-automated grant discovery and proposal generation could reduce weeks of research to hours. The potential is real even if unrealized.' },
    competitivePositioningIndex: 25,
    competitivePositioningBreakdown: { inputs: { internalFit: 28, externalFit: 22, dynamicFit: 25, differentiationClarity: 25 }, formula: 'weighted avg', score: 25, rationale: 'Emerging space (Instrumentl, OpenGrants exist). Differentiation angle unclear — business plan mentions AI matching but no implementation.' },
    businessModelStrength: 30,
    businessModelBreakdown: { inputs: { revenueModelClarity: 35, moatDepth: 22, scalability: 38, customerRelationshipDepth: 22 }, formula: 'weighted avg', score: 30, rationale: 'Business plan exists with SaaS model concept. Grant data CSV shows research depth. No validated revenue, no product, no customers.' },
    dataScienceReadiness: 18,
    dataScienceBreakdown: { inputs: { dataAvailability: 25, instrumentationCoverage: 12, modelingCapability: 15, rigorLevel: 18 }, formula: 'weighted avg', score: 18, rationale: 'Grant CSV file is the only data artifact. No pipeline, no model, no instrumentation. Starting from scratch.' },
    architectureResilience: 12,
    architectureResilienceBreakdown: { inputs: { modularity: 12, testCoverage: 8, observability: 12, recoverability: 15 }, formula: 'weighted avg', score: 12, rationale: 'No code to assess. Files are documents and CSVs. Architecture is a future concern.' },
    strategicAdvantageComposite: 30,
    strategicAdvantageBreakdown: { inputs: {}, formula: 'weighted composite', score: 30, rationale: 'Highest-opportunity problem in portfolio (WTP=72, cost reduction potential=70) but lowest execution stage (no code). This is pure optionality. The gap between problem value and solution maturity is the largest in the portfolio.' },
    calculatedAt: '2026-04-27T04:00:00Z',
    calculationVersion: '2.0.0',
  },
};

export const MOCK_PROPOSALS: ImprovementProposal[] = [
  {
    id: 'prop-001',
    projectId: 'balam-licitaciones',
    title: 'Implementar pipeline de análisis semántico con embeddings',
    context: 'Las licitaciones se analizan con búsqueda de texto exacto. El matching semántico mejoraría el recall en ~40%.',
    evidence: ['búsqueda actual falla para sinónimos legales', 'competidores usan RAG embeddings'],
    expectedImpact: 'Aumenta cobertura de matching de 60% a ~85%. Sube WTP percibido.',
    risk: 'Costo de embeddings API si volumen crece. Requiere modelo de calidad.',
    riskLevel: 'medium',
    acceptanceCriteria: ['Recall@10 > 0.85 en test set', 'Costo < $0.02/búsqueda'],
    changeType: 'architecture',
    affectedComponents: ['search-engine', 'ingestion-pipeline'],
    strategicMapping: {
      raisesWTP: true,
      reducesCost: false,
      increasesSwitchingCosts: true,
      improvesActivitySystem: true,
      strengthensBusinessModel: true,
      senseTransmitPhase: 'Analyze',
      recognizeRequestPhase: 'Respond',
    },
    status: 'approved',
    requiresHumanApproval: false,
    createdAt: '2026-04-20T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
  },
  {
    id: 'prop-002',
    projectId: 'balam-licitaciones',
    title: 'Sistema de alertas proactivas por sector y monto',
    context: 'Usuarios deben revisar manualmente. Alertas automáticas reducirían esfuerzo y aumentarían retención.',
    evidence: ['NPS bajo en "descubrimiento de oportunidades"', 'feature request #1 en feedback'],
    expectedImpact: 'Coach-behavior activado. Reduce abandono en -25%. Aumenta DAU.',
    risk: 'Notificaciones mal calibradas = spam = churn.',
    riskLevel: 'low',
    acceptanceCriteria: ['Opt-out < 10%', 'CTR alertas > 30%'],
    changeType: 'feature',
    affectedComponents: ['notification-service', 'user-preferences'],
    strategicMapping: {
      raisesWTP: true,
      reducesCost: false,
      increasesSwitchingCosts: true,
      improvesActivitySystem: false,
      strengthensBusinessModel: false,
      senseTransmitPhase: 'React',
      recognizeRequestPhase: 'Respond',
    },
    status: 'draft',
    requiresHumanApproval: true,
    createdAt: '2026-04-21T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
  },
  {
    id: 'prop-003',
    projectId: 'balam-licitaciones',
    title: 'Módulo de análisis causal: correlación vs causalidad en tendencias',
    context: 'Los dashboards muestran correlaciones sin distinguir causalidad. Riesgo de decisiones erróneas.',
    evidence: ['MITx DS rigor standards', 'usuario tomó decisión basada en correlación espuria'],
    expectedImpact: 'Reduce riesgo decisional. Sube posicionamiento competitivo como plataforma de rigor analítico.',
    risk: 'Alto esfuerzo. Requiere estadístico/data scientist senior.',
    riskLevel: 'high',
    acceptanceCriteria: ['Al menos 3 análisis causales validados en producción'],
    changeType: 'data',
    affectedComponents: ['analytics-engine', 'dashboard-reports'],
    strategicMapping: {
      raisesWTP: true,
      reducesCost: false,
      increasesSwitchingCosts: true,
      improvesActivitySystem: true,
      strengthensBusinessModel: true,
      senseTransmitPhase: 'Analyze',
      recognizeRequestPhase: 'Recognize',
    },
    status: 'draft',
    requiresHumanApproval: true,
    createdAt: '2026-04-22T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
  },
];

export const MOCK_LANDSCAPE: CompetitiveLandscape = {
  projectId: 'balam-licitaciones',
  competitors: [
    { id: 'c1', name: 'CompraNet MX', strengths: ['volumen', 'oficial'], weaknesses: ['UX pobre', 'sin análisis'], wtpPosition: 'lower', costPosition: 'lower', switchingCostLevel: 'low', updatedAt: '2026-04-22T00:00:00Z' },
    { id: 'c2', name: 'Mercado Público CL', strengths: ['integración gobierno', 'API'], weaknesses: ['solo Chile', 'sin IA'], wtpPosition: 'similar', costPosition: 'similar', switchingCostLevel: 'medium', updatedAt: '2026-04-22T00:00:00Z' },
    { id: 'c3', name: 'Probol BO', strengths: ['precio', 'soporte'], weaknesses: ['sin ML', 'sin embeddings'], wtpPosition: 'lower', costPosition: 'lower', switchingCostLevel: 'low', updatedAt: '2026-04-22T00:00:00Z' },
  ],
  internalFit: 'Alto — pipeline de ingesta + RAG + dashboards se refuerzan mutuamente',
  externalFit: 'Moderado — WTP claro para analistas, menos para distribuidores nuevos',
  dynamicFit: 'Moderado — arquitectura local-first permite evolución rápida',
  activitySystem: [
    { id: 'as1', label: 'Ingesta automatizada', description: 'Conectores multiportal que alimentan el índice', isCore: true, reinforces: ['as2', 'as3'] },
    { id: 'as2', label: 'RAG + Embeddings', description: 'Matching semántico sobre corpus legal', isCore: true, reinforces: ['as3', 'as4'] },
    { id: 'as3', label: 'Alertas proactivas', description: 'Coach-behavior por sector y monto', isCore: false, reinforces: ['as4'] },
    { id: 'as4', label: 'Pipeline de partners', description: 'Gestión de relaciones con proveedores', isCore: false, reinforces: ['as1'] },
  ],
  wtpNarrative: 'Usuarios pagan por reducir tiempo de búsqueda y aumentar hit-rate en licitaciones relevantes.',
  costNarrative: 'Automatización de ingesta reduce costo marginal. Escala sin crecimiento proporcional de equipo.',
  differentiationChoices: ['Cobertura multi-país LATAM', 'Análisis semántico vs keyword', 'Local-first con AI'],
  convergenceRisks: ['Portales oficiales añadiendo analytics', 'GPT wrappers genéricos de búsqueda'],
  updatedAt: '2026-04-22T00:00:00Z',
};

export const MOCK_BM: BusinessModelProfile = {
  projectId: 'balam-licitaciones',
  valueProposition: 'Inteligencia de mercado de licitaciones LATAM: más oportunidades, menos tiempo, mejor decisión.',
  targetCustomerSegments: ['Fabricantes OEM LATAM', 'Distribuidores de equipos', 'Analistas de compras gubernamentales'],
  revenueStreams: ['SaaS mensual por rol', 'API access para enterprise', 'Reportes custom'],
  costStructure: ['Ingesta automatizada (low marginal)', 'AI API (usage-based)', 'Soporte (low-touch)'],
  keyResources: ['Corpus legal multi-país', 'Modelo de embeddings fine-tuned', 'Network de usuarios verificados'],
  keyActivities: ['Ingesta y normalización diaria', 'Mejora continua de RAG', 'Onboarding de nuevos portales'],
  keyPartners: ['Portales gubernamentales (data feed)', 'Proveedores de LLM', 'Integradores enterprise'],
  channels: ['Direct (demo → trial)', 'Partnerships con cámaras de comercio', 'Content SEO técnico'],
  customerRelationships: ['Self-serve onboarding', 'Success manager para enterprise', 'Comunidad de analistas'],
  connectedStrategyType: 'coach-behavior',
  moatSources: ['Corpus multi-país exclusivo', 'Embeddings entrenados en dominio legal', 'Network effects en pipeline'],
  activitySystem: [],
  updatedAt: '2026-04-22T00:00:00Z',
};
