/**
 * @cs/reporting — exporters.ts
 * Functions to render report objects to Markdown and print-friendly HTML.
 * Worker: SET-06
 */

import type { PortfolioReport, ProjectReport, ProposalReport, ReportSection } from './types.js';

// ─── Shared helpers ───────────────────────────────────────────────────────────

type AnyReport = PortfolioReport | ProjectReport | ProposalReport;

function scoreBar(score: number): string {
  const filled = Math.round(score / 10);
  return '█'.repeat(filled) + '░'.repeat(10 - filled) + ` ${score}/100`;
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return iso;
  }
}

// ─── Markdown exporter ────────────────────────────────────────────────────────

/**
 * Convert any report object to a readable Markdown string.
 * Suitable for saving as .md files or pasting into docs.
 */
export function exportToMarkdown(report: AnyReport): string {
  const lines: string[] = [];

  lines.push(`# ${report.meta.title}`);
  lines.push('');
  lines.push(`> **Type:** ${report.meta.type} | **Generated:** ${formatDate(report.meta.generatedAt)} | **Template:** \`${report.meta.templateId}\``);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const section of report.sections) {
    lines.push(`## ${section.title}`);
    lines.push('');
    renderSectionMarkdown(section, lines);
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by @cs/reporting v${report.meta.generatorVersion}*`);

  return lines.join('\n');
}

function renderSectionMarkdown(section: ReportSection, lines: string[]): void {
  const c = section.content as Record<string, unknown>;
  if (!c) return;

  switch (section.id) {
    case 'executive-summary': {
      for (const [key, val] of Object.entries(c)) {
        if (Array.isArray(val)) {
          lines.push(`**${formatKey(key)}:**`);
          for (const item of val as unknown[]) {
            if (typeof item === 'object' && item !== null) {
              const obj = item as Record<string, unknown>;
              lines.push(`- ${Object.values(obj).join(' — ')}`);
            } else {
              lines.push(`- ${String(item)}`);
            }
          }
        } else {
          lines.push(`**${formatKey(key)}:** ${String(val)}`);
        }
      }
      break;
    }

    case 'scoring-breakdown': {
      const metrics = c['metrics'] as Array<{
        name: string; score: number; formula: string; rationale: string;
        inputs: Record<string, number>;
      }>;
      if (metrics) {
        lines.push('| Dimension | Score | Bar |');
        lines.push('|-----------|-------|-----|');
        for (const m of metrics) {
          lines.push(`| ${m.name} | ${m.score} | ${scoreBar(m.score)} |`);
        }
        lines.push('');
        for (const m of metrics) {
          lines.push(`### ${m.name}`);
          lines.push(`- **Score:** ${m.score}/100`);
          lines.push(`- **Formula:** \`${m.formula}\``);
          lines.push(`- **Rationale:** ${m.rationale}`);
          const inputEntries = Object.entries(m.inputs);
          if (inputEntries.length > 0) {
            lines.push('- **Inputs:**');
            for (const [k, v] of inputEntries) {
              lines.push(`  - \`${k}\`: ${v}`);
            }
          }
          lines.push('');
        }
      }
      break;
    }

    case 'worksheet-completion': {
      const wss = c['worksheets'] as Array<{
        worksheetTitle: string; answeredCount: number; totalQuestions: number;
        completedAt: string | undefined;
      }>;
      if (wss) {
        lines.push('| Worksheet | Progress | Completed |');
        lines.push('|-----------|----------|-----------|');
        for (const w of wss) {
          const pct = w.totalQuestions > 0
            ? Math.round((w.answeredCount / w.totalQuestions) * 100)
            : 0;
          lines.push(
            `| ${w.worksheetTitle} | ${w.answeredCount}/${w.totalQuestions} (${pct}%) | ${w.completedAt ? formatDate(w.completedAt) : 'Pending'} |`,
          );
        }
      }
      break;
    }

    case 'improvement-proposals': {
      const props = c['proposals'] as Array<{
        title: string; status: string; riskLevel: string; changeType: string;
      }>;
      if (props && props.length > 0) {
        lines.push('| Title | Status | Risk | Type |');
        lines.push('|-------|--------|------|------|');
        for (const p of props) {
          lines.push(`| ${p.title} | ${p.status} | ${p.riskLevel} | ${p.changeType} |`);
        }
      } else {
        lines.push('*No proposals found.*');
      }
      break;
    }

    case 'evidence-summary': {
      const evidence = c['linkedEvidence'] as Array<{
        type: string; reference: string; description: string; confidence: string;
      }>;
      const raw = c['rawEvidence'] as string[];
      if (raw && raw.length > 0) {
        lines.push('**Raw Evidence:**');
        for (const e of raw) {
          lines.push(`- ${e}`);
        }
        lines.push('');
      }
      if (evidence && evidence.length > 0) {
        lines.push('**Linked Evidence:**');
        lines.push('| Type | Reference | Confidence |');
        lines.push('|------|-----------|------------|');
        for (const e of evidence) {
          lines.push(`| ${e.type} | ${e.reference} | ${e.confidence} |`);
        }
      }
      break;
    }

    case 'acceptance-criteria': {
      const criteria = c['criteria'] as string[];
      if (criteria) {
        for (const cr of criteria) {
          lines.push(`- [ ] ${cr}`);
        }
      }
      break;
    }

    case 'risk-analysis': {
      lines.push(`**Risk Level:** ${String(c['riskLevel'])}`);
      lines.push('');
      lines.push(`**Risk Description:** ${String(c['risk'])}`);
      if (c['rollbackPlan']) {
        lines.push('');
        lines.push(`**Rollback Plan:** ${String(c['rollbackPlan'])}`);
      }
      break;
    }

    case 'project-rankings': {
      const ranked = c['ranked'] as Array<{ projectName: string; strategicAdvantage: number }>;
      if (ranked) {
        lines.push('| Rank | Project | Score |');
        lines.push('|------|---------|-------|');
        ranked.forEach((r, i) => {
          lines.push(`| ${i + 1} | ${r.projectName} | ${r.strategicAdvantage} |`);
        });
      }
      break;
    }

    default: {
      // Generic key-value rendering for all other sections
      for (const [key, val] of Object.entries(c)) {
        if (Array.isArray(val)) {
          lines.push(`**${formatKey(key)}:**`);
          for (const item of val as unknown[]) {
            lines.push(`- ${JSON.stringify(item)}`);
          }
        } else if (typeof val === 'object' && val !== null) {
          lines.push(`**${formatKey(key)}:** (see below)`);
          lines.push('```json');
          lines.push(JSON.stringify(val, null, 2));
          lines.push('```');
        } else {
          lines.push(`**${formatKey(key)}:** ${String(val)}`);
        }
      }
    }
  }
}

function formatKey(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (s) => s.toUpperCase())
    .trim();
}

// ─── HTML exporter ────────────────────────────────────────────────────────────

const PRINT_CSS = `
  @media print {
    body { margin: 0; font-size: 11pt; }
    .no-print { display: none !important; }
    .page-break { page-break-before: always; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #ccc; padding: 6px 8px; }
    h1, h2, h3 { page-break-after: avoid; }
  }
`;

const SCREEN_CSS = `
  * { box-sizing: border-box; }
  body {
    font-family: 'Inter', 'Segoe UI', system-ui, sans-serif;
    background: #0f1117;
    color: #e2e8f0;
    margin: 0;
    padding: 0;
  }
  .report-container {
    max-width: 960px;
    margin: 0 auto;
    padding: 40px 32px;
  }
  header {
    border-bottom: 2px solid #4f46e5;
    padding-bottom: 24px;
    margin-bottom: 40px;
  }
  h1 { color: #a5b4fc; font-size: 2rem; margin: 0 0 8px 0; }
  .meta { color: #94a3b8; font-size: 0.85rem; }
  h2 { color: #818cf8; font-size: 1.3rem; margin: 32px 0 12px 0; border-bottom: 1px solid #1e293b; padding-bottom: 6px; }
  h3 { color: #c4b5fd; font-size: 1rem; margin: 20px 0 8px 0; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.875rem; }
  th { background: #1e293b; color: #94a3b8; text-align: left; padding: 8px 12px; border-bottom: 2px solid #334155; }
  td { padding: 8px 12px; border-bottom: 1px solid #1e293b; }
  tr:hover td { background: #161b2e; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
  .badge-risk-low { background: #14532d; color: #86efac; }
  .badge-risk-medium { background: #7c4500; color: #fcd34d; }
  .badge-risk-high { background: #7f1d1d; color: #fca5a5; }
  .score-bar { font-family: monospace; color: #818cf8; }
  .score-num { font-weight: 700; color: #e2e8f0; }
  ul { padding-left: 20px; }
  li { margin-bottom: 4px; line-height: 1.5; }
  blockquote { border-left: 3px solid #4f46e5; padding-left: 16px; color: #94a3b8; margin: 16px 0; }
  code { background: #1e293b; padding: 2px 6px; border-radius: 4px; font-size: 0.85em; }
  .section-card { background: #0d1117; border: 1px solid #1e293b; border-radius: 8px; padding: 20px 24px; margin-bottom: 24px; }
  footer { color: #475569; font-size: 0.75rem; margin-top: 40px; padding-top: 16px; border-top: 1px solid #1e293b; }
`;

/**
 * Convert any report object to a complete, print-friendly HTML string.
 * Includes @media print CSS rules for PDF export.
 */
export function exportToHtml(report: AnyReport): string {
  const sections = report.sections.map((s) => renderSectionHtml(s)).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="${escapeHtml(report.meta.title)} — Connected Strategy report" />
  <title>${escapeHtml(report.meta.title)}</title>
  <style>
${SCREEN_CSS}
${PRINT_CSS}
  </style>
</head>
<body>
  <div class="report-container">
    <header>
      <h1>${escapeHtml(report.meta.title)}</h1>
      <p class="meta">
        Type: <strong>${report.meta.type}</strong> &nbsp;|&nbsp;
        Generated: <strong>${formatDate(report.meta.generatedAt)}</strong> &nbsp;|&nbsp;
        Template: <code>${escapeHtml(report.meta.templateId)}</code> &nbsp;|&nbsp;
        Version: <code>${escapeHtml(report.meta.generatorVersion)}</code>
      </p>
    </header>

    <main>
${sections}
    </main>

    <footer>
      Generated by @cs/reporting v${escapeHtml(report.meta.generatorVersion)} &mdash; Connected Strategy Platform
    </footer>
  </div>
</body>
</html>`;
}

function renderSectionHtml(section: ReportSection): string {
  const content = renderSectionContentHtml(section);
  return `    <div class="section-card">
      <h2>${escapeHtml(section.title)}</h2>
      ${content}
    </div>`;
}

function renderSectionContentHtml(section: ReportSection): string {
  const c = section.content as Record<string, unknown>;
  if (!c) return '<p><em>No content.</em></p>';

  switch (section.id) {
    case 'executive-summary': {
      const rows = Object.entries(c)
        .filter(([, v]) => !Array.isArray(v) && typeof v !== 'object')
        .map(
          ([k, v]) =>
            `<tr><th>${escapeHtml(formatKey(k))}</th><td>${escapeHtml(String(v))}</td></tr>`,
        )
        .join('\n');
      const arrays = Object.entries(c).filter(([, v]) => Array.isArray(v));
      const arrayHtml = arrays
        .map(
          ([k, v]) =>
            `<h3>${escapeHtml(formatKey(k))}</h3><ul>${(v as unknown[])
              .map((item) => {
                if (typeof item === 'object' && item !== null) {
                  return `<li>${Object.values(item as Record<string, unknown>)
                    .map((x) => escapeHtml(String(x)))
                    .join(' — ')}</li>`;
                }
                return `<li>${escapeHtml(String(item))}</li>`;
              })
              .join('')}</ul>`,
        )
        .join('\n');
      return `<table>${rows}</table>${arrayHtml}`;
    }

    case 'scoring-breakdown': {
      const metrics = c['metrics'] as Array<{
        name: string; score: number; formula: string; rationale: string;
        inputs: Record<string, number>;
      }>;
      if (!metrics) return '';
      const rows = metrics
        .map(
          (m) =>
            `<tr>
              <td>${escapeHtml(m.name)}</td>
              <td class="score-num">${m.score}</td>
              <td class="score-bar">${scoreBar(m.score)}</td>
            </tr>`,
        )
        .join('\n');
      const details = metrics
        .map(
          (m) =>
            `<h3>${escapeHtml(m.name)}</h3>
            <blockquote>${escapeHtml(m.rationale)}</blockquote>
            <p>Formula: <code>${escapeHtml(m.formula)}</code></p>`,
        )
        .join('\n');
      return `<table><thead><tr><th>Dimension</th><th>Score</th><th>Bar</th></tr></thead><tbody>${rows}</tbody></table>${details}`;
    }

    case 'worksheet-completion': {
      const wss = c['worksheets'] as Array<{
        worksheetTitle: string; answeredCount: number; totalQuestions: number;
        completedAt: string | undefined;
      }>;
      if (!wss) return '';
      const rows = wss
        .map((w) => {
          const pct = w.totalQuestions > 0
            ? Math.round((w.answeredCount / w.totalQuestions) * 100)
            : 0;
          return `<tr>
            <td>${escapeHtml(w.worksheetTitle)}</td>
            <td>${w.answeredCount}/${w.totalQuestions} (${pct}%)</td>
            <td>${w.completedAt ? formatDate(w.completedAt) : '<em>Pending</em>'}</td>
          </tr>`;
        })
        .join('\n');
      return `<table><thead><tr><th>Worksheet</th><th>Progress</th><th>Completed</th></tr></thead><tbody>${rows}</tbody></table>`;
    }

    case 'improvement-proposals': {
      const props = c['proposals'] as Array<{
        title: string; status: string; riskLevel: string; changeType: string;
      }>;
      if (!props || props.length === 0) return '<p><em>No proposals found.</em></p>';
      const rows = props
        .map(
          (p) =>
            `<tr>
              <td>${escapeHtml(p.title)}</td>
              <td>${escapeHtml(p.status)}</td>
              <td><span class="badge badge-risk-${p.riskLevel}">${escapeHtml(p.riskLevel)}</span></td>
              <td>${escapeHtml(p.changeType)}</td>
            </tr>`,
        )
        .join('\n');
      return `<table><thead><tr><th>Title</th><th>Status</th><th>Risk</th><th>Type</th></tr></thead><tbody>${rows}</tbody></table>`;
    }

    case 'evidence-summary': {
      const raw = c['rawEvidence'] as string[];
      const linked = c['linkedEvidence'] as Array<{
        type: string; reference: string; description: string; confidence: string;
      }>;
      let html = '';
      if (raw && raw.length > 0) {
        html += `<h3>Raw Evidence</h3><ul>${raw.map((e) => `<li>${escapeHtml(e)}</li>`).join('')}</ul>`;
      }
      if (linked && linked.length > 0) {
        const rows = linked
          .map(
            (e) =>
              `<tr><td>${escapeHtml(e.type)}</td><td><code>${escapeHtml(e.reference)}</code></td><td>${escapeHtml(e.confidence)}</td></tr>`,
          )
          .join('\n');
        html += `<h3>Linked Evidence</h3><table><thead><tr><th>Type</th><th>Reference</th><th>Confidence</th></tr></thead><tbody>${rows}</tbody></table>`;
      }
      return html || '<p><em>No evidence attached.</em></p>';
    }

    case 'acceptance-criteria': {
      const criteria = c['criteria'] as string[];
      if (!criteria || criteria.length === 0) return '<p><em>No criteria defined.</em></p>';
      return `<ul>${criteria.map((cr) => `<li>☐ ${escapeHtml(cr)}</li>`).join('')}</ul>`;
    }

    case 'risk-analysis': {
      const riskClass = `badge badge-risk-${String(c['riskLevel'])}`;
      return `
        <p><strong>Risk Level:</strong> <span class="${riskClass}">${escapeHtml(String(c['riskLevel']))}</span></p>
        <p>${escapeHtml(String(c['risk']))}</p>
        ${c['rollbackPlan'] ? `<h3>Rollback Plan</h3><p>${escapeHtml(String(c['rollbackPlan']))}</p>` : ''}
      `;
    }

    case 'project-rankings': {
      const ranked = c['ranked'] as Array<{ projectName: string; strategicAdvantage: number }>;
      if (!ranked) return '';
      const rows = ranked
        .map(
          (r, i) =>
            `<tr><td>${i + 1}</td><td>${escapeHtml(r.projectName)}</td><td class="score-num">${r.strategicAdvantage}</td></tr>`,
        )
        .join('\n');
      return `<table><thead><tr><th>Rank</th><th>Project</th><th>Score</th></tr></thead><tbody>${rows}</tbody></table>`;
    }

    default: {
      // Generic key-value rendering
      const rows = Object.entries(c)
        .map(([k, v]) => {
          const val = Array.isArray(v)
            ? `<ul>${(v as unknown[]).map((x) => `<li>${escapeHtml(JSON.stringify(x))}</li>`).join('')}</ul>`
            : typeof v === 'object' && v !== null
            ? `<pre><code>${escapeHtml(JSON.stringify(v, null, 2))}</code></pre>`
            : escapeHtml(String(v));
          return `<tr><th>${escapeHtml(formatKey(k))}</th><td>${val}</td></tr>`;
        })
        .join('\n');
      return `<table>${rows}</table>`;
    }
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
