/**
 * @cs/agents — v3/harness-reviewer.ts
 *
 * Implements the "Semantic Reviewer" Harness Engineering pattern.
 * Uncensored open-source models (like Llama 3 or Qwen) can hallucinate or fail
 * strict formatting constraints. This pattern uses a two-pass approach:
 *
 * 1. Implementer Pass: The model generates the JSON response.
 * 2. Reviewer Pass: The model audits its own response against semantic constraints
 *    and fixes hallucinations or formatting errors before returning.
 */

import type { z } from 'zod';
import type { LLMProvider } from '../llm-provider.js';
import { callLLMValidated } from './llm-validated.js';

export interface ReviewerConstraints {
  /** Explicit rules the reviewer must check against (e.g., "Do not invent new companies") */
  semanticRules: string[];
  /** Is this a high-risk agent that requires the double-pass? */
  isRequired: boolean;
}

/**
 * Two-pass LLM call implementing the Harness Engineering Reviewer pattern.
 */
export async function callLLMWithReviewer<T>(
  provider: LLMProvider,
  prompt: string,
  schema: z.ZodType<T>,
  opts: { temperature: number; maxOutputTokens: number },
  constraints?: ReviewerConstraints
): Promise<T> {
  
  // If reviewer is not required or not provided, just do a normal validated call
  if (!constraints?.isRequired) {
    return callLLMValidated(provider, prompt, schema, opts);
  }

  console.log(`[Harness] 🛡️ Starting Implementer pass with model: ${provider.model}`);
  
  // PASS 1: Implementer generates the first draft
  // We use callLLMValidated to ensure it at least parses as valid JSON
  const draftResult = await callLLMValidated(provider, prompt, schema, {
    temperature: opts.temperature,
    maxOutputTokens: opts.maxOutputTokens
  });

  console.log(`[Harness] 🔍 Starting Reviewer pass...`);

  // PASS 2: Reviewer audits the draft against the semantic rules
  const rulesList = constraints.semanticRules.map(r => `- ${r}`).join('\n');
  const draftJson = JSON.stringify(draftResult, null, 2);

  const reviewerPrompt = `
You are a ruthless, expert QA Reviewer for a Connected Strategy consulting firm.
Your job is to audit a JSON output generated by a junior consultant to ensure it strictly follows these semantic rules:

CRITICAL RULES:
${rulesList}

DRAFT JSON TO REVIEW:
\`\`\`json
${draftJson}
\`\`\`

ORIGINAL INSTRUCTIONS GIVEN TO JUNIOR:
${prompt}

TASK:
1. Analyze the Draft JSON against the Critical Rules.
2. If it violates ANY rule or hallucinates information not present in the original input, FIX IT.
3. If it perfectly follows the rules, output it exactly as is.

Respond ONLY with the final, corrected JSON. Do not include any other text.
`;

  // The reviewer must also return valid JSON matching the schema
  const finalResult = await callLLMValidated(provider, reviewerPrompt, schema, {
    temperature: 0.1, // Reviewer should be very deterministic
    maxOutputTokens: opts.maxOutputTokens
  });

  console.log(`[Harness] ✅ Reviewer pass complete.`);
  return finalResult;
}
