/**
 * @cs/prompt-packets — index.ts
 * Full implementation of the prompt packet engine.
 * Produces ready-to-paste prompts for Codex (plan) and Antigravity (execution).
 * Worker: SET-06
 */

import type { ImprovementProposal } from '@cs/domain';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface PromptPacket {
  id: string;
  proposalId: string;
  type: 'codex_plan' | 'antigravity_execution';
  context: string;
  evidence: string;
  objective: string;
  constraints: string[];
  affectedFiles: string[];
  acceptanceCriteria: string;
  risks: string[];
  expectedTests: string[];
  generatedAt: string;
  /** Ready-to-paste markdown prompt string */
  markdown: string;
}

// ─── In-memory store (demo mode — in production, back with DB) ────────────────

const packetStore = new Map<string, PromptPacket>();

// ─── Core generator ───────────────────────────────────────────────────────────

/**
 * Generate a PromptPacket from an ImprovementProposal.
 *
 * For `codex_plan`: detailed, multi-file, architectural context suitable for Codex.
 * For `antigravity_execution`: focused, scoped, direct execution prompt.
 */
export function generatePacketFromProposal(
  proposal: ImprovementProposal,
  type: 'codex_plan' | 'antigravity_execution',
): PromptPacket {
  const id = `pp-${type}-${proposal.id}-${Date.now()}`;
  const generatedAt = new Date().toISOString();

  const evidence = proposal.evidence.length > 0
    ? proposal.evidence.join('\n- ')
    : 'No direct evidence attached — infer from context.';

  const constraints: string[] = [
    'Stay within the stated write scope.',
    'Do not modify files outside the affected components list.',
    'All changes must remain TypeScript-strict compliant.',
    'No new runtime dependencies without explicit approval.',
    ...buildStrategicConstraints(proposal),
  ];

  const risks: string[] = [
    `Risk level declared by analyst: **${proposal.riskLevel.toUpperCase()}**`,
    `Stated risk: ${proposal.risk}`,
    ...(proposal.rollbackPlan ? [`Rollback plan: ${proposal.rollbackPlan}`] : []),
  ];

  const expectedTests: string[] = buildExpectedTests(proposal);

  const packet: Omit<PromptPacket, 'markdown'> = {
    id,
    proposalId: proposal.id,
    type,
    context: proposal.context,
    evidence,
    objective: proposal.expectedImpact,
    constraints,
    affectedFiles: proposal.affectedComponents,
    acceptanceCriteria: proposal.acceptanceCriteria.join('\n- '),
    risks,
    expectedTests,
    generatedAt,
  };

  const markdown = type === 'codex_plan'
    ? buildCodexPlanPrompt(proposal, packet as PromptPacket)
    : buildAntigravityPrompt(proposal, packet as PromptPacket);

  const full: PromptPacket = { ...packet, markdown };
  packetStore.set(id, full);
  return full;
}

/**
 * Lightweight generator by proposalId + type only.
 * Returns null if no matching proposal data is available (requires proposal to be passed).
 * @deprecated Use generatePacketFromProposal instead.
 */
export function generatePacket(
  _proposalId: string,
  _type: 'codex_plan' | 'antigravity_execution',
): PromptPacket | null {
  return null; // Stub: call generatePacketFromProposal with the full proposal object
}

/**
 * Convert a PromptPacket to a ready-to-paste markdown string.
 * The packet already contains .markdown — this function is an explicit re-render.
 */
export function toMarkdown(packet: PromptPacket): string {
  return packet.markdown;
}

/**
 * Retrieve a previously generated packet by ID.
 */
export function getPacketById(id: string): PromptPacket | undefined {
  return packetStore.get(id);
}

/**
 * List all packets generated in this session.
 */
export function listPackets(): PromptPacket[] {
  return [...packetStore.values()];
}

// ─── Codex plan prompt builder ────────────────────────────────────────────────

function buildCodexPlanPrompt(
  proposal: ImprovementProposal,
  packet: PromptPacket,
): string {
  const strategicFlags = buildStrategicFlagsMd(proposal);

  return `# CODEX_PLAN_PROMPT

> **Generated by:** @cs/prompt-packets — Connected Strategy Platform
> **Packet ID:** \`${packet.id}\`
> **Proposal ID:** \`${packet.proposalId}\`
> **Generated at:** ${packet.generatedAt}

---

## Role

You are an expert software architect and connected strategy engineer. You will produce a **structured implementation plan** for the following improvement proposal. Do not write code yet — produce a plan with clear phases, file list, and verification steps.

---

## Context

${packet.context}

---

## Evidence

- ${packet.evidence}

---

## Objective

${packet.objective}

---

## Strategic Mapping

${strategicFlags}

---

## Affected Files / Components

${packet.affectedFiles.length > 0
  ? packet.affectedFiles.map((f) => `- \`${f}\``).join('\n')
  : '- *(to be determined during planning)*'}

---

## Constraints

${packet.constraints.map((c) => `- ${c}`).join('\n')}

---

## Acceptance Criteria

- ${packet.acceptanceCriteria}

---

## Risks

${packet.risks.map((r) => `- ${r}`).join('\n')}

---

## Expected Tests

${packet.expectedTests.length > 0
  ? packet.expectedTests.map((t) => `- [ ] ${t}`).join('\n')
  : '- [ ] At minimum: typecheck must pass after changes\n- [ ] At minimum: existing tests must not regress'}

---

## Required Deliverable

Produce a **phased implementation plan** with:

1. **Phase breakdown** (e.g., Phase 1: Setup, Phase 2: Core logic, Phase 3: Integration, Phase 4: Verification)
2. **File list** (create / modify / delete per phase)
3. **Key decisions** that need to be made before implementation
4. **Verification commands** to run after each phase
5. **Rollback procedure** if implementation fails

${proposal.validationPlan ? `\n## Validation Plan (from analyst)\n\n${proposal.validationPlan}\n` : ''}

---

*This prompt was generated by the Connected Strategy Platform. Paste it directly into Codex.*
`;
}

// ─── Antigravity execution prompt builder ─────────────────────────────────────

function buildAntigravityPrompt(
  proposal: ImprovementProposal,
  packet: PromptPacket,
): string {
  return `# ANTIGRAVITY_EXECUTION_PROMPT

> **Generated by:** @cs/prompt-packets — Connected Strategy Platform
> **Packet ID:** \`${packet.id}\`
> **Proposal ID:** \`${packet.proposalId}\`
> **Generated at:** ${packet.generatedAt}

---

## Task

Implement the following scoped improvement. This is a **direct execution prompt** — no planning phase needed. Implement, verify, and report done.

---

## Objective

${packet.objective}

---

## Context

${packet.context}

---

## Evidence

- ${packet.evidence}

---

## Write Scope (exclusive)

${packet.affectedFiles.length > 0
  ? packet.affectedFiles.map((f) => `- \`${f}\``).join('\n')
  : '- *(see context for scope)*'}

## Do NOT touch

- Any file not listed above
- \`CURRENT_STATE.md\`, \`CURRENT_TASK.md\`, \`CHANGELOG_PROJECT.md\`

---

## Acceptance Criteria

- ${packet.acceptanceCriteria}

---

## Constraints

${packet.constraints.slice(0, 4).map((c) => `- ${c}`).join('\n')}

---

## Risk: ${proposal.riskLevel.toUpperCase()}

${proposal.risk}

---

## Verification

Run after implementation:

${packet.expectedTests.length > 0
  ? packet.expectedTests.map((t) => `- [ ] ${t}`).join('\n')
  : '- [ ] pnpm typecheck\n- [ ] Confirm no existing tests regress'}

---

## End condition

Write exactly:
\`\`\`
LISTO
\`\`\`

Do not ask the human any questions.

---

*This prompt was generated by the Connected Strategy Platform. Paste it directly into Antigravity.*
`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildStrategicConstraints(proposal: ImprovementProposal): string[] {
  const flags: string[] = [];
  const m = proposal.strategicMapping;
  if (m.raisesWTP) flags.push('Must demonstrably raise WTP (willingness to pay).');
  if (m.reducesCost) flags.push('Must reduce operational cost — verify with metrics.');
  if (m.increasesSwitchingCosts) flags.push('Must increase switching costs — data lock or habit formation.');
  if (m.improvesActivitySystem) flags.push('Must improve internal activity system fit.');
  if (m.strengthensBusinessModel) flags.push('Must strengthen the business model — document how.');
  return flags;
}

function buildStrategicFlagsMd(proposal: ImprovementProposal): string {
  const m = proposal.strategicMapping;
  return [
    `- Raises WTP: ${m.raisesWTP ? '✅ YES' : '❌ No'}`,
    `- Reduces Cost: ${m.reducesCost ? '✅ YES' : '❌ No'}`,
    `- Increases Switching Costs: ${m.increasesSwitchingCosts ? '✅ YES' : '❌ No'}`,
    `- Improves Activity System: ${m.improvesActivitySystem ? '✅ YES' : '❌ No'}`,
    `- Strengthens Business Model: ${m.strengthensBusinessModel ? '✅ YES' : '❌ No'}`,
    `- Sense/Transmit Phase: **${m.senseTransmitPhase}**`,
    `- Recognize/Request Phase: **${m.recognizeRequestPhase}**`,
  ].join('\n');
}

function buildExpectedTests(proposal: ImprovementProposal): string[] {
  const tests: string[] = [];
  const type = proposal.changeType;

  tests.push('pnpm --filter <affected-package> typecheck');

  if (type === 'feature' || type === 'ui') {
    tests.push('Visual inspection: render the new feature and confirm it matches acceptance criteria.');
    tests.push('No console errors in browser devtools.');
  }
  if (type === 'architecture' || type === 'infra') {
    tests.push('pnpm build — full monorepo build must pass.');
    tests.push('Health endpoint returns ok after changes.');
  }
  if (type === 'data') {
    tests.push('Data migration script runs without errors.');
    tests.push('Read-back verify: data written is correctly retrieved.');
  }
  if (type === 'process') {
    tests.push('End-to-end workflow walkthrough: complete the process described in acceptance criteria.');
  }
  if (type === 'docs') {
    tests.push('All referenced files exist and links are valid.');
  }

  // Always add acceptance criteria as tests
  for (const cr of proposal.acceptanceCriteria) {
    tests.push(cr);
  }

  return tests;
}
